accounts/urls.py
from django.urls import path

from .views import LoginUser, LogoutUser, CreateUser, Profile, CreateAddress, ListAddress, UpdateAddress, DeleteAddress
# TODO: add reset password

app_name = "accounts"



urlpatterns = [
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", LogoutUser.as_view(), name="logout"),
    path("sign-up/", CreateUser.as_view(), name="signin"),
    path("profile/", Profile.as_view(), name="profile"),
    path("address/create", CreateAddress.as_view(), name="address-create"),
    path("address/list", ListAddress.as_view(), name="address-list"),
    path("address/update/<int:id>", UpdateAddress.as_view(), name="address-update"),
    path("address/delete/<int:id>", DeleteAddress.as_view(), name="address-delete"),
]

basket/urls.py
from django.urls import path
from .views import ShowBasket, AddToBasket


app_name = "basket"

urlpatterns = [
    path("", ShowBasket.as_view(), name="show"),
    path("add/", AddToBasket.as_view(), name="add"),
]

digikala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",include("products.urls")),
    path("admin/", admin.site.urls),
    path("basket/",include("basket.urls")),
    path("accounts/",include("accounts.urls")),
    path("shipping/",include("shipping.urls")),
    path("transactions/",include("transaction.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import CreateProvider, CategoryView, HomeView, ProductDetails, ViewPerCategory, CreateReview, AddBookmark

app_name = "product"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("provider/", CreateProvider.as_view(), name="create-provider"),
    
    path("product/<uuid:pid>", ProductDetails.as_view(), name="details"),
    path("product/bookmark/<uuid:pid>", AddBookmark.as_view(), name="bookmark"),
    path("product/<uuid:pid>/review", CreateReview.as_view(), name="review"),
    
    path("categories/<slug:category>", ViewPerCategory.as_view(), name="products_category"),
    path("categories/", CategoryView.as_view(), name="categories"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext as _

import uuid

from .managers import CustomUserManager

class User(AbstractUser):
    CONSUMER = 1
    PROVIDER = 2

    user_type =(
        (CONSUMER, "consumer"),
        (PROVIDER, "provider"),
    )
    
    email = models.EmailField(verbose_name=_("Email"), max_length=100, unique=True)
    phone_number = models.CharField(_("Phone number "), max_length=12, unique=True)
    firstname = models.CharField(verbose_name=_("First Name"), max_length=40, blank=False)
    lastname = models.CharField(verbose_name=_("Last Name"), max_length=50)
    score = models.PositiveIntegerField(verbose_name=_("Score"), default=0)
    uuid = models.UUIDField(verbose_name=_("uuid"), default=uuid.uuid4)
    user_type = models.PositiveSmallIntegerField(_("User Type"),choices=user_type, default=CONSUMER)
    birth_date = models.DateField(verbose_name=_("Birth date"), null=True)
    is_staff = models.BooleanField(
        _("Staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )

    is_active = models.BooleanField(
        _("Active"),
        default=True,
        help_text=_("Designates whether this user should be treated as active. "),
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ("firstname", "lastname", "phone_number")

    objects = CustomUserManager()

    def is_provider(self):
        if self.user_type == 2:
            return True
        return False
    
    def __str__(self):
        return self.email

class Address(models.Model):
    user = models.ForeignKey(User, verbose_name=_("User"), on_delete=models.CASCADE, related_name="addresses")
    address = models.TextField(null=False, blank=False)
    zip_code = models.CharField(max_length=14)
    city = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=12)
    receiver_name = models.CharField(max_length=50)
    
    def __str__(self):
        return f"|receiver:{self.receiver_name}- addr: {self.address} zipCode: {self.zip_code}"

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _
from .models import Address

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ("phone_number",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = UserChangeForm.Meta.fields
        
class UserLoginForm(forms.Form):
    email_phone = forms.CharField(max_length=50, min_length=6, required=True)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput)
    



class AddressCreationForm(forms.ModelForm):
    class Meta():
        model = Address
        fields = ("address", "zip_code", "city", "phone_number", "receiver_name")


class CustomUserSignInForm(forms.ModelForm):
    password2 = forms.CharField(required=True)
    class Meta():
        
        model = User
        fields = ( "firstname", "lastname", "phone_number","email","password","password2" )

accounts/views.py
import re
from django.forms.models import BaseModelForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import FormView, View, TemplateView, CreateView, ListView, UpdateView, DeleteView

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User, Address 
from .forms import UserLoginForm, CustomUserSignInForm, AddressCreationForm
from basket.views import basket_merge_after_login
from transaction.models import Transactions, Wallet

EMAIL_REGEX = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
PHONE_REGEX = r'^0[1-9][0-9]{9}$'

class LoginUser(FormView):
    form_class = UserLoginForm
    success_url = "/"
    template_name = "accounts/login.html"
    
    def post(self, request, *args, **kwargs):
        
        form = UserLoginForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data["password"]
            username = form.cleaned_data["email_phone"]
            if re.match(EMAIL_REGEX, username):
                user = authenticate(request, email=username, password=password)
            elif re.match(PHONE_REGEX, username):
                user = User.objects.get(phone_number=username)
                if not user.check_password(password):
                    form.add_error('password', 'Incorrect password for this phone number')
                    return render(request, self.template_name, {"form":form})
            if user is not None:
                login(self.request, user)
                response = HttpResponseRedirect(request.GET.get("next", "/"))
                basket = basket_merge_after_login(user, self.request)
                if basket is not None:
                    response.set_cookie("basket_id", basket.pk)
                return response 
            else:
                return render(request, self.template_name, {"form":form})
        return render(request, self.template_name, {"form":self.form_class})

class CreateUser(FormView):
    template_name = "accounts/signup.html"
    success_url = "/"
    form_class = CustomUserSignInForm
    
    def post(self, request, *args, **kwargs):
        form = CustomUserSignInForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data["password"]
            password2 = form.cleaned_data["password2"]
            phone_number = form.cleaned_data["phone_number"]
            lastname = form.cleaned_data["lastname"]
            firstname = form.cleaned_data["firstname"]
            email = form.cleaned_data["email"]
            if password2 != password:
                form.add_error("password", "passwords dont match")
            elif not re.match(EMAIL_REGEX, email):
                form.add_error("email", "email is wrong")
            elif not re.match(PHONE_REGEX, phone_number):
                form.add_error("phone_number", "phone number is wrong")
            if len(form.errors) > 0:
                return render(request, self.template_name, {"form":form})
            user = User.objects.create(email=email, username=email, phone_number=phone_number, firstname=firstname, lastname=lastname)
            user.set_password(password)
            user.save()
            login(self.request, user)
            return redirect(request.POST.get("next", "/"))
        return render(request, self.template_name, {"form":form})

class LogoutUser(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        logout(self.request)
        response = HttpResponseRedirect("/")
        response.set_cookie('basket_id', '', max_age=0)
        return response
    
class Profile(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        user = User.objects.prefetch_related("addresses", "bookmarks", "basket").get(pk=self.request.user.pk) 
        ctx["user"] = user    
        ctx["address"] = user.addresses.all()
        ctx["bookmarks"] = user.bookmarks.all()
        ctx["last_products"] = user.basket.filter(is_paid=True) # last products user bought
        ctx["score"] = Transactions.calc_user_score(user.email)
        Wallet.update_wallet(user)
        w, _ = Wallet.objects.get_or_create(user=user)
        ctx["wallet"] = w
        return ctx

class CreateAddress(CreateView):
    form_class = AddressCreationForm
    context_object_name = "form"
    template_name = "accounts/address.html"
    success_url = "/accounts/profile"
    model = Address
    
    
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        addr = form.save(commit=False)
        addr.user = self.request.user
        addr.save()
        return HttpResponseRedirect(self.success_url)
    

class ListAddress(ListView):
    template_name = "accounts/address_list.html"
    context_object_name = "addresses"
    
    def get_queryset(self):
        queryset = Address.objects.filter(user=self.request.user)
        return queryset
    
class UpdateAddress(UpdateView):
    form_class = AddressCreationForm
    template_name = "accounts/address_update.html"
    context_object_name = "addresses"
    pk_url_kwarg = "id"
    success_url = "/accounts/profile"
    
    
    def get_queryset(self):
        id = self.kwargs["id"]
        queryset = Address.objects.filter(pk=id) 
        return queryset
    

class DeleteAddress(DeleteView):
    pk_url_kwarg = "id"
    success_url = "/accounts/profile"
    
    def get_queryset(self):
        id = self.kwargs["id"]
        queryset = Address.objects.filter(pk=id) 
        return queryset
    
    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        obj.delete()
        return HttpResponseRedirect(self.success_url)

templates/accounts/address.html
{% extends 'base.html' %}   

{% block title  %}
  login
{% endblock title %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="create">
  </form>
{% endblock body %}

templates/accounts/address_list.html
{% extends "base.html" %}
{% block title %}
    addr list
{% endblock title %}

{% block body %}
  
  {% for addr in addresses %}
    <p> address {{addr.address}} </p>
    <p> zipCode {{addr.zip_code}} </p>
    <p> city {{addr.city}} </p>
    <p> receiver_name {{addr.receiver_name}} </p>
    <p> phone_number {{addr.phone_number}} </p>
    <button>
      <a href="{% url 'accounts:address-update' addr.pk %}">update</a>
    </button>
    <button>
      <a href="{% url 'accounts:address-delete' addr.pk %}">delete</a>
    </button>
  {% endfor %}
  <br><a href="{% url 'accounts:profile' %}">go back</a>
    
{% endblock body %}

templates/accounts/address_update.html
{% extends 'base.html' %}   

{% block title  %}
  login
{% endblock title %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="create">
  </form>
{% endblock body %}

templates/accounts/login.html
{% extends 'base.html' %}   

{% block title  %}
  login
{% endblock title %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="login">
  </form>
{% endblock body %}

templates/accounts/profile.html
{% extends 'base.html' %}   

{% block title  %}
  Profile
{% endblock title %}

{% load custom_format %}
{% block body %}


  <h1>{{user.firstname}}'s profile </h1>

    <b>hello {{user.firstname}} {{user.lastname}}</b>
    <h3>Balance: {{wallet.total|c_format}}</h3>
    <p>score:{{score}}</p>
    <p>Joined at {{user.date_joined.date}}</p>
    <p>score : {{user.score}}</p>
    <p>born at {{user.birth_date}}</p>
    <p> phone: {{user.phone_number}} </p>
    <h1>manage addresses</h1>
    <a href="{% url 'accounts:address-list' %}">address list</a>
    <h3>Bookmark</h3>
    {% for bookmark in bookmarks %}
        <a href="{% url 'product:details' bookmark.product.pid %}">{{bookmark.product}}</a><br>
    {% endfor %}
    <h3> user address </h3>
    {% for addr in address %}
        <p>address : {{addr.address}}</p>
        <p> city: {{addr.city}} - zipCode: {{addr.zip_code}} </p>
        <p> phone number: {{addr.phone_number}}</p>
        <p>receiver_name: {{addr.receiver_name}}</p>
    {% endfor %}
    <h3>products you bought</h3>
    {% for prod in last_products %}
      <h4>products in basket {{prod.created_at.date}}</h4>
      {% for p in prod.lines.all %}
        <p><a href="{% url 'product:details' p.product.pid %}">{{p.product}} </a> - {{p.quantity}}</p>
      {% endfor %}
        
    {% endfor %}
{% endblock body %}

templates/accounts/signup.html
{% extends 'base.html' %}   

{% block title  %}
  login
{% endblock title %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="signin">
  </form>
{% endblock body %}