basket/urls.py
from django.urls import path
from .views import ShowBasket, AddToBasket


app_name = "basket"

urlpatterns = [
    path("", ShowBasket.as_view(), name="show"),
    path("add/", AddToBasket.as_view(), name="add"),
]

digikala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",include("products.urls")),
    path("admin/", admin.site.urls),
    path("basket/",include("basket.urls")),
    path("accounts/",include("accounts.urls")),
    path("shipping/",include("shipping.urls")),
    path("transactions/",include("transaction.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import CreateProvider, CategoryView, HomeView, ProductDetails, ViewPerCategory, CreateReview, AddBookmark

app_name = "product"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("provider/", CreateProvider.as_view(), name="create-provider"),
    
    path("product/<uuid:pid>", ProductDetails.as_view(), name="details"),
    path("product/bookmark/<uuid:pid>", AddBookmark.as_view(), name="bookmark"),
    path("product/<uuid:pid>/review", CreateReview.as_view(), name="review"),
    
    path("categories/<slug:category>", ViewPerCategory.as_view(), name="products_category"),
    path("categories/", CategoryView.as_view(), name="categories"),
]

products/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from uuid import uuid4
from utils import rate_validator
User = get_user_model()



class Category(models.Model):
    title = models.CharField(max_length=40)
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.title


class Provider(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    provider_name = models.CharField(max_length=50, unique=True)
    joined = models.DateField(auto_now_add=True)
    address = models.TextField()
    working_perm_id = models.CharField(max_length=14, unique=True)
    owner_national_code = models.CharField(max_length=15, unique=True)
    location = models.CharField(max_length=40, null=True)
    def __str__(self):
        return self.provider_name
    
    # performance = models
    
    
class Product(models.Model):
    title = models.CharField(_("Title"), max_length=120, unique=True)
    pid = models.UUIDField(_("Pid"), default=uuid4, unique=True)
    description = models.TextField()
    price = models.DecimalField(verbose_name=_("Price") , max_digits=10, decimal_places=2)
    in_digikala_inventory = models.BooleanField(default=False)
    in_provider_inventory = models.BooleanField(default=True)
    provider = models.ManyToManyField(Provider)
    category = models.ForeignKey(Category, verbose_name=_("Category"), on_delete=models.PROTECT)
    
    
    def __str__(self):
        return self.title
    

class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product_images/')

class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="reviews")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reviews")
    rating = models.PositiveIntegerField(validators=[rate_validator.validate_rate]) 
    review = models.TextField(blank=True, null=True)
    created_date = models.DateField(auto_now_add=True)
    recommend = models.BooleanField(default=True)
    is_anon = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.product} - {self.user}"
    
    
class ReviewImage(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='review_images/')

class Bookmark(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="bookmarks")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bookmarks")
    class Meta:
        unique_together = ("product", "user")

products/forms.py
from .models import Provider, Review, ReviewImage
from django import forms


class ProviderForm(forms.ModelForm):
    class Meta:
        model = Provider
        fields = ("provider_name", "address", "working_perm_id", "owner_national_code")
        

class ReviewForm(forms.ModelForm):
    images = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

    class Meta:
        model = Review
        fields = ['rating', 'review', 'recommend', 'is_anon']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['images'].widget.attrs.update({'accept': 'image/*'})
    

        

products/views.py
from typing import Any
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from django.db.models import Avg, Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import FormView, ListView, View, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from .forms import ProviderForm, ReviewForm
from .models import Category, Product, ReviewImage, Bookmark

# using a simple view because thats all i need
class CategoryView(View):
    
        
    @method_decorator(cache_page(60 * 15))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    
    def get(self, request, *args, **kwargs):
        c = Category.objects.all()   
        return render(request, "products/categories.html", {"categories":c})

class ViewPerCategory(ListView):
    
    template_name = "products/product_category.html"    
    context_object_name = "products"
    
    def get_queryset(self):
        slug = self.kwargs["category"]
        search_query = self.request.GET.get('search')
        if search_query:
            return Product.objects.filter(Q(title__icontains=search_query) & Q(category__slug=slug))
        return Product.objects.filter(category__slug=slug)
    
    
class AddBookmark(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        p = self.kwargs["pid"]
        product = Product.objects.get(pid=p)
        try:
            Bookmark.objects.create(user=self.request.user,product=product)
            return redirect(self.request.POST.get("next", "/"))
        except IntegrityError:
            bookmark = Bookmark.objects.filter(Q(product=product) & Q(user= self.request.user)).first()
            bookmark.delete()
            return redirect(self.request.POST.get("next", "/"))
            
    

class HomeView(ListView):
    context_object_name = "products"
    template_name = "products/home.html"
    
    def get_queryset(self):
        queryset = Product.objects.all()
        category = self.request.GET.get('category')
        if category:
            queryset = queryset.filter(category=category)
        search_query = self.request.GET.get('search')
        if search_query:
            queryset = queryset.filter(title__icontains=search_query)
        if not search_query and not category:
            # returning top products if user is not searching for a specific product
            queryset = Product.objects.annotate(avg_rating=Avg('reviews__rating')).filter(avg_rating__gt=3)
        return queryset
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx["categories"] = Category.objects.all()  
        return ctx


class ProductDetails(DetailView):
    template_name = "products/product_detail.html"
    context_object_name = "product"
    model = Product
    slug_field = "pid"
    slug_url_kwarg = "pid"
    
    @method_decorator(cache_page(60 * 15))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    
    def get_queryset(self):
        # queryset = super().get_queryset()
        pid = self.kwargs["pid"]
        product = Product.objects.filter(pid=pid)
        return product
    
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        qs = self.get_queryset()
        p = ctx["product"]
        ctx["review_form"] = ReviewForm()
        ctx["reviews"] = p.reviews.all()
        if len(ctx["reviews"]) > 0:
            ctx["avg_rate"] = round(sum([i.rating for i in ctx["reviews"]])/len(ctx["reviews"]), 2)
        else:
            ctx["avg_rate"] = 0.0
        return ctx


class CreateReview(LoginRequiredMixin, FormView):
    
    def post(self, request, *args, **kwargs) :
        form = ReviewForm(data=request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = self.request.user
            review.product = Product.objects.get(pid=self.kwargs["pid"])
            review.save()
            
            images = request.FILES.getlist("images")
            for image in images:
                ReviewImage.objects.create(review=review, image=image)
                
            return redirect(request.POST.get("next", "/"))
        return redirect(request.POST.get("next", "/"))
    


class CreateProvider(FormView):
    template_name = "products/create_provider.html"
    success_url = "/"
    form_class = ProviderForm
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_provider():
            
            return super().dispatch(request, *args, **kwargs)
        return redirect('/')
    
    def form_valid(self, form: Any) -> HttpResponse:
        provider = form.save(commit=False)
        provider.user = self.request.user
        provider.save()
        return redirect(self.success_url)

templates/products/categories.html
{% extends "base.html" %}   

{% block title %}
categories list
{% endblock title %}

{% block body %}

{% for category in categories %}
<h3><a href="{% url 'product:products_category' category.slug %}">{{category}} </a> </h3> <br>
{% endfor %}


{% endblock body %}

templates/products/create_provider.html
{% extends "base.html" %}   

{% block title %}
create provider
{% endblock title %}    


{% block body %}
<form method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="ok">
</form>

{% endblock body %}

templates/products/home.html
{% extends 'base.html' %}   


{% block title %}
    Home
{% endblock title %}


{% block body %}
    {{request.user}}
    <form method="get">
        <select name="category">
            <option value="" selected>All Categories</option>
            
            {% for c in categories %}
                <option value="{{c.id}}" selected>{{c.title}}</option>
            {% endfor %}
                
        </select>
        <input type="text" name="search" placeholder="Search products">
        <button type="submit">Apply Filters</button>
    </form>

    
    {% for product in products %}
        <h3><a href="{%url 'product:details' product.pid%}">{{product.title}}</a> - {{product.price}}$</h3>
        
        {% if product.in_digikala_inventory %}
            <p>in in digikala inventory</p>
        {% endif %}
        {% if product.in_provider_inventory %}
            <p>in provider inventory</p>
        {% endif %}
            
    {% endfor %}
        
    
{% endblock body %}
    

templates/products/product_category.html
{% extends 'base.html' %}   


{% block title %}
    products
{% endblock title %}


{% block body %}
    
    <form method="get">
    
        <input type="text" name="search" placeholder="Search products">
        <button type="submit">Apply Filters</button>
    </form>

    
    {% for product in products %}
        <h3><a href="{%url 'product:details' product.pid%}">{{product.title}}</a> - {{product.price}}$</h3>
        
        {% if product.in_digikala_inventory %}
            <p>in in digikala inventory</p>
        {% endif %}
        {% if product.in_provider_inventory %}
            <p>in provider inventory</p>
        {% endif %}
            
    {% endfor %}
        
    
{% endblock body %}
    

templates/products/product_detail.html
{% extends 'base.html' %}

{% block title %}
  detail
{% endblock title %}

{% block body %}
<h1>{{product.title}}</h1>
 <h3> {{product.price}}</h3><br>

{% if product.images.all %}
  {% for image in product.images.all %}
    <img src="{{image.image.url}}" style="height: 150px;width:100px">
  {% endfor %}
{% endif %}

<h3> rating:->{{avg_rate}} </h3>
 <h2> description </h2>
 <p>{{product.description}}</p>
<h3> category :=: {{product.category}} </h3>

<h4>Providers:</h4>
<ul>
  {% for provider in product.provider.all %}
    <li>{{ provider }} </li>
  {% endfor %}
</ul>
<form method="post" action="{% url 'product:bookmark' product.pid %}">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{request.path}}">
  <input type="submit"  value="Bookmark">
</form>
<form method="post" action="{% url 'basket:add' %}">
  {% csrf_token %}

  <input type="hidden" name="next" value="{{request.path}}">
  <input type="hidden" name="product" value="{{product.id}}">
  <input type="number" name="quantity">
  <input type="submit"  value="add to basket">
</form>



<h2>Reviews</h2>
{% for review in reviews %}

  {% if review.images.all %}
    {% for image in review.images.all %}
      <img src="{{image.image.url}}" style="height: 150px;width:100px">
    {% endfor %}
  {% endif %}

    
    {% if review.is_anon %}
      <p>Anon user - rated:{{review.rating}}- at: {{review.created_date}} :</p>
    {% else %}
      <p>{{review.user}} - rated:{{review.rating}}- at: {{review.created_date}} :</p>
    {% endif %}
      
    
    {% if review.recommend %}
      <h4>recommended</h4>
    {% else %}
      <h4>not recommended</h4>
    {% endif %}
    <p>{{review.review}}</p>
{% endfor %}
  <h2>
    Add a review
  </h2>
  <form method="post" enctype="multipart/form-data" action="{% url 'product:review' product.pid %}">
    {% csrf_token %}
    {{review_form.as_p}}
    <input type="hidden" name="product" value="{{product}}">
    
    <input type="hidden" name="next" value="{{request.path}}">
    <input type="submit"  value="comment">
  </form>

  {% if review_form.errors %}
  <div class="alert alert-danger">
      <p>Please correct the following errors:</p>
      {{ review_form.errors }}
  </div>
{% endif %}
  
{% endblock body %}