accounts/urls.py
from django.urls import path

from .views import LoginUser, LogoutUser, CreateUser, Profile, CreateAddress, ListAddress, UpdateAddress, DeleteAddress
# TODO: add reset password

app_name = "accounts"



urlpatterns = [
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", LogoutUser.as_view(), name="logout"),
    path("sign-up/", CreateUser.as_view(), name="signin"),
    path("profile/", Profile.as_view(), name="profile"),
    path("address/create", CreateAddress.as_view(), name="address-create"),
    path("address/list", ListAddress.as_view(), name="address-list"),
    path("address/update/<int:id>", UpdateAddress.as_view(), name="address-update"),
    path("address/delete/<int:id>", DeleteAddress.as_view(), name="address-delete"),
]

basket/urls.py
from django.urls import path
from .views import ShowBasket, AddToBasket


app_name = "basket"

urlpatterns = [
    path("", ShowBasket.as_view(), name="show"),
    path("add/", AddToBasket.as_view(), name="add"),
]

digikala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",include("products.urls")),
    path("admin/", admin.site.urls),
    path("basket/",include("basket.urls")),
    path("accounts/",include("accounts.urls")),
    path("shipping/",include("shipping.urls")),
    path("transactions/",include("transaction.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import CreateProvider, CategoryView, HomeView, ProductDetails, ViewPerCategory, CreateReview, AddBookmark

app_name = "product"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("provider/", CreateProvider.as_view(), name="create-provider"),
    
    path("product/<uuid:pid>", ProductDetails.as_view(), name="details"),
    path("product/bookmark/<uuid:pid>", AddBookmark.as_view(), name="bookmark"),
    path("product/<uuid:pid>/review", CreateReview.as_view(), name="review"),
    
    path("categories/<slug:category>", ViewPerCategory.as_view(), name="products_category"),
    path("categories/", CategoryView.as_view(), name="categories"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Base.css' %}">
</head>
<body>

<nav class="navbar">
        <ul class="nav-list">
            <li class="nav-item"><a href="{% url 'product:home' %}">Home</a></li>

            {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'accounts:profile' %}">profile</a></li>

                <li class="nav-item"><a href="{% url 'accounts:logout' %}">Logout</a></li>

            {% else %}
                <li class="nav-item"><a href="{% url 'accounts:login' %}">Login</a></li>
                <li class="nav-item"><a href="{% url 'accounts:signin' %}">Sign Up</a></li>
            {% endif %}
                <li class="nav-item"><a href="{% url 'basket:show' %}">Basket</a></li>
        </ul>
    </nav>

    {% block body %}{% endblock body %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj %}
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current-page">page: {{ page_obj.number }}</span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
                            
            {% else %}
                <span class="current-page">page: 1</span>
            {% endif %}
        </span>
    </div>

    <script src="" async defer></script>
</body>
</html>